### ISSUE TITLE
Sequential Testing of Contexts

### ISSUE THREAD

**Issue by blengerich** [cnellington/Contextualized#204]
It might be nice to have a utility function that cycles through a bunch of potential contexts to do sequential univariate testing.

**Comment by cnellington** [comment]
Clarification for @aaron10l: We've made tests previously that show when incorporating contextual effects are meaningful (Ben added these tests in PR #182 and #179). Now, we'd like to determine which contexts are meaningful and which are not. One way to do this could be trimming the context to a single feature and applying Ben's test to see if contextualization matters for this feature. This could be repeated for all context features, and then the p-values can be corrected for multiple testing.
