### ISSUE TITLE
Add plotting util for heterogeneous effects.

### ISSUE THREAD

**Issue by blengerich** [cnellington/Contextualized#37]
Plot the influence of each covariate on the predicted regression coefficients. Can be done by passing the empirical training set into the model and plotting the marginalization of coefficient against covariate (if GAM encoder, this is exact). 

Example can be found here: https://github.com/blengerich/ContextualizedGAM/blob/main/plot_utils.py
Example outputs here: https://docs.google.com/presentation/d/1NlyFF2GleaB-tp6toT2kJuGHEyG1o2dEbF07RVd2KXE/edit#slide=id.g10fc0285f3c_0_27

**Comment by cnellington** [comment]
Closing, implemented in scContextualized
