### ISSUE TITLE
Clarify Demo

### ISSUE THREAD

**Issue by blengerich** [cnellington/Contextualized#91]
From user requests:

- Might be nice to build from simple to more complicated (e.g., start with 1 context, 1 drug dose, etc).
- Do negative doses make sense? Does Contextualized.ML expect centered X variables?
- Figures could be clarified (e.g. Pull apart explanations of context in sub-figures?)
- Phrase “Per dose” is not entirely clear -- is that the coefficient or the partial sum?

**Comment by tbkwatkins** [comment]
Examples query specific clusters by context
