### ISSUE TITLE
Easier early stopping in easy module

### ISSUE THREAD

**Issue by blengerich** [cnellington/Contextualized#95]
Right now, we have to pass in `callback_constructors` kwarg to the SKLearnWrapper, but it may be more intuitive for users to just specify the patience instead.

**Comment by cnellington** [comment]
Related to #133 , has this been resolved @blengerich ?

**Comment by blengerich** [comment]
In `dev` but not `main`. Let's close when dev->main is pulled.

**Comment by blengerich** [comment]
Closing now because it's merged. Early stopping is controlled with `es_monitor`, `es_mode`, `es_patience`, `es_min_delta`, and `es_verbose` keyword arguments.
