### ISSUE TITLE
Linear encoder

### ISSUE THREAD

**Issue by blengerich** [cnellington/Contextualized#97]
It'd be great to have a convenience for linear encoders. This could be done by having a NGAM with depth 1 and width 1, or by creating a new encoder class with a flat beta.

**Comment by blengerich** [comment]
Where is it enabled? I'm hoping for an encoder called something like `Linear` available in `contextualized.modules.ENCODERS`.

**Comment by cnellington** [comment]
I see, it's enabled using an MLP with layers=1 so we can easily add this to the Encoders.
